name: material_3_tools
description: Utils that simplify usage of Material Design 3 (M3) theming available in Flutter
version: 0.0.1
homepage: https://github.com/notDmDrl/material_3_tools
repository: https://github.com/notDmDrl/material_3_tools

environment:
  sdk: ">=2.17.0-0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  material_color_utilities: ^0.2.0

dev_dependencies:
  very_good_analysis: ^3.1.0