name: material_3_tools
description: Utils that simplify usage of Material Design 3 (M3) theming available in Flutter
version: 0.0.6
homepage: https://github.com/notDmDrl/material_3_tools
repository: https://github.com/notDmDrl/material_3_tools

environment:
  sdk: ">=3.3.0-0 <4.0.0"
  flutter: ">=3.17.0-0"

dependencies:
  flutter:
    sdk: flutter

  material_color_utilities: 0.8.0
  animations: 2.0.8

dev_dependencies:
  very_good_analysis: ^5.1.0
